version: '3.8'

services:
  backend:
    build: ./backend
    container_name: appointment_backend
    command: >
      sh -c "python manage.py migrate && 
             python manage.py collectstatic --noinput && 
             python manage.py populate_db --no-clear && 
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - ./backend:/app
      # This line is updated to point to 'staticfiles'
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - SECRET_KEY=your-super-secret-key-for-docker
      - DEBUG=0

  frontend:
    build: ./frontend
    container_name: appointment_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume: