# Generated by Django 5.2.1 on 2025-05-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='time_range',
            field=models.CharField(default='slot-based', max_length=100),
            preserve_default=False,
        ),
    ]
